### PR TITLE
#18: Mongo v6/7 Official Images

### PR DESCRIPTION
**Pull request by reynoldsalec**
- Refactor plugin layout and add bitnami-powered Mongo 6/7 versions.
- Run official Mongo images for versions above 5.
- Add 6/7 tests to github actions, feed linter.

### CODE REVIEW

**Comment by reynoldsalec** [comment]
Apologies @pirog if some of this code is a little dirty, I will clean as you see fit.

**Comment by reynoldsalec** [comment]
Fixes #18

**Comment by curzio-della-santa** [comment]
@reynoldsalec  Thanks for the great job, tested `6.0` and works

A few small questions:
1. Why did you not change node version to 16 in the main lando file? (I could not do anything without this step)
2. Any idea when lando will officially support it and change the content of the [mongo plugin page](https://docs.lando.dev/mongo/development.html)
3. Why can't use `mongo:6` instead of  `mongo:6.0`? (should set an alias somewhere?)

**Comment by reynoldsalec** [comment]
@curzio-della-santa sorry I missed your questions!

RE: 1, the `/.lando.yml` at the root of the project is just for building docs; actually we just updated that to node 18 across all projects, since we're updating all Lando stuff to Node 18.

RE: 2, that was _just_ updated as well :)

RE: 3, you're correct, in `builders/mongo.js` you'll see the support versions follow a `x.0` syntax: https://github.com/lando/mongo/blob/main/builders/mongo.js#L13, would be a great little PR if you're interested!

RE:4, I think the only reason I kept Mongo 5 on the old Bitnami versions was to prevent breaking changes for people using the old images...if we rolled out an update moving to the official images, likely anyone who does a `lando rebuild` on their old `mongo:5` using app will lose their data. Once we release Lando 4.x services everything will be off Bitnami for good (thank god).

**Pull request merged**
